services:
  - type: web
    name: racha
    env: python
    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "flask db upgrade"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: FLASK_ENV
        value: production